Kapt to ksp -- fails
Dunno why

All works except removing `kotlin("kapt")`` from `plugins {}`` section gives

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':app:compileDebugJavaWithJavac'.
    > javax.annotation.processing.FilerException: Attempt to recreate a file for type my.package.Cache_AttemptsDao_Impl

    ...

    * Exception is:
    org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileDebugJavaWithJavac'.
        ...
    Caused by: javax.annotation.processing.FilerException: Attempt to recreate a file for type my.package.Cache_AttemptsDao_Impl
        at jdk.compiler/com.sun.tools.javac.processing.JavacFiler.checkNameAndExistence(JavacFiler.java:732)
        at jdk.compiler/com.sun.tools.javac.processing.JavacFiler.createSourceOrClassFile(JavacFiler.java:498)
        at jdk.compiler/com.sun.tools.javac.processing.JavacFiler.createSourceFile(JavacFiler.java:435)
        at org.gradle.api.internal.tasks.compile.processing.IncrementalFiler.createSourceFile(IncrementalFiler.java:45)
        at com.squareup.javapoet.JavaFile.writeTo(JavaFile.java:169)
        at androidx.room.compiler.processing.javac.JavacFiler.write(JavacFiler.kt:32)
        at androidx.room.compiler.processing.XFilerKt.writeTo(XFiler.kt:48)
        at androidx.room.compiler.processing.XFilerKt.writeTo(XFiler.kt:62)
        at androidx.room.compiler.processing.XFilerKt.writeTo$default(XFiler.kt:55)
        at androidx.room.writer.TypeWriter.write(TypeWriter.kt:78)
        at androidx.room.DatabaseProcessingStep.process(DatabaseProcessingStep.kt:98)
        at androidx.room.compiler.processing.CommonProcessorDelegate.processRound(XBasicAnnotationProcessor.kt:123)
        at androidx.room.compiler.processing.javac.JavacBasicAnnotationProcessor.process(JavacBasicAnnotationProcessor.kt:71)
        at org.gradle.api.internal.tasks.compile.processing.DelegatingProcessor.process(DelegatingProcessor.java:62)
        ...